/*
 *   Copyright (C) 2009 Free Software Foundation, Inc.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

/* This is generated by autoconf */
#include "config.h"

#include <getopt.h>
#include <dejagnu.h>
#include <string.h>

#include "gnuae.h"
#include "gui.h"

static void usage (const char *);

int
main(int argc, char **argv)
{
    long id = 0;
    const char *name = "Guitest run";
    const char *des1 = "ignore this run";
    const char *des2 = "this run is done";
    project_t proj1;
    project_t *proj2 = 0;

    // Initialixe GnuAE, but use the test database
    gui_init_db("gnuaetest");

    // First test the C API for manipulating project data
    proj1.name = name;
    proj1.description = des1;
    proj1.sunhours = 0.0;
    proj1.windhours = 0.0;
    proj1.windspeed = 0.0;
    proj1.location = "none";
    proj1.latitude = 1.2;
    proj1.longitude = 2.3;
    
    id = gui_new_project(&proj1);
    if (id > 0) {
	pass("gui_new_project()");
    } else {
	fail("gui_new_project()");
    }
    
    proj2 = gui_get_project(id, name);
    if (proj2) {
	if (proj2->description, des1) {
	    pass("gui_get_project()");
	} else {
	    fail("gui_get_project()");
	}
    } else {
	unresolved("gui_get_project()");
    }

    /* change some data */
    proj1.description = des2;
    proj1.latitude = proj1.latitude * 2;
    proj1.longitude = proj1.longitude * 2;

    /* update an existing record */
    gui_update_project(id, &proj1);
    proj2 = gui_get_project(id, name);
    if (proj2) {
	if (strcmp(proj2->description, des2) == 0) {
	    pass("gui_update_project()");
	} else {
	    fail("gui_update_project()");
	}
    } else {
	unresolved("gui_update_project()");
    }

    /* erase the record we just added */
    gui_erase_project(id, name);
    /* make sure it's gone */
    proj2 = gui_get_project(id, name);
    if (proj2) {
	fail("gui_erase_project()");
    } else {
	pass("gui_erase_project()");
    }

    // Then test the C API for manipulating loads
    
    gui_list_names("loads");

    // We're all done
    totals();
}

static void
usage (const char *prog)
{
    printf("Usage: %s ", prog);
    printf("-h\tHelp");
    exit (-1);
}

// local Variables:
// mode: C
// indent-tabs-mode: t
// End:
