// 
//   Copyright (C) 2009 Free Software Foundation, Inc.
// 
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

// This is generated by autoconf
#include "config.h"

#include <getopt.h>

#include "dejagnu.h"
#include "gui.h"

static void usage (const char *);

int
main(int argc, char **argv) {


}

static void
usage (const char *prog)
{
    printf("Usage: %s ", prog);
    printf("-h\tHelp");
    exit (-1);
}

// local Variables:
// mode: C
// indent-tabs-mode: t
// End:
