// This is generated by autoconf
#include "config.h"
 
#include <cstdio>
#include <cstddef>
#include <cstring>

#include "err.h"
 
// Testing support
#include "dejagnu.h"
 
using namespace std;
 
TestState runtest;
int verbosity;

static void usage (void);

int
main(int argc, char *argv[])
{
   int c;
   bool dump;
   
    while ((c = getopt (argc, argv, "hvsp:m:")) != -1) {
    switch (c) {
    case 'h':
      usage ();
      break;
                                                                                
    case 'd':
      dump = true;
      break;
      
    case 'v':
      verbosity++;
      break;
                                                                                
    default:
      usage ();
      break;
    }
  }
                                                                                
  // get the file name from the command line
  if (optind < argc) {
    //    procname = argv[optind];
    //      cout << "Will use \"" << procname << "\" for demo " << endl;
  }
   }
                                                                                
static void
usage (void)
{
    cerr << "This program tests the NEC code calculations." << endl;
    cerr << "Usage: tnec [hvd] filename" << endl;
    cerr << "-h\tHelp" << endl;
    cerr << "-d\tdump table 8" << endl;
    cerr << "-v\tverbose" << endl;
    exit (-1);
}
