/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_MainWindow (void);
GtkWidget* create_about (void);
GtkWidget* create_pvdata (void);
GtkWidget* create_gtkplotwin (void);
GtkWidget* create_fileselection (void);
GtkWidget* create_gtkplot2Dwin (void);
GtkWidget* create_gtkplot3Dwin (void);
GtkWidget* create_neccalc (void);
GtkWidget* create_col_list4 (void);
GtkWidget* create_col_list5 (void);
GtkWidget* create_col_list6 (void);
GtkWidget* create_col_list3 (void);
GtkWidget* create_PVBrowser (void);
GtkWidget* create_LoadWin (void);
GtkWidget* create_ChooseLoads (void);
GtkWidget* create_WiringWIndow (void);
GtkWidget* create_InverterBrowser (void);
GtkWidget* create_ChargerWindow (void);
GtkWidget* create_CombinerWindow (void);
GtkWidget* create_BatteryWindow (void);
GtkWidget* create_text_dialog (void);
GtkWidget* create_AddPVWin (void);
