// 
//   Copyright (C) 2003 Free Software Foundation, Inc.
//
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation; either version 2 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//

// This is generated by autoconf
#include "config.h"

#include <sys/types.h>
#include <sys/stat.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <gtk/gtkstatusbar.h>
#ifdef USE_GTKPLOT
#include <gtkextra/gtkplot.h>
#include <gtkextra/gtkplot3d.h>
#include <gtkextra/gtkplotdata.h>
#include <gtkextra/gtkplotsurface.h>
#include <gtkextra/gtkplotcsurface.h>
#include <gtkextra/gtkplotcanvas.h>
#include <gtkextra/gtkplotps.h>
#endif

#include "system_data.h"
#include "callbacks.h"
#include "interface.h"
#include "support.h"

extern GtkWidget *MainWindow;
extern wire_data_t wiredata;


/*
  Read in a system config file. This loads all the combo boxes with
  our last choices.
 */
int
read_system(const char *filespec)
{
  GtkWidget *entry;
  gchar *lineptr;
  char *home;
  char *buf;
  FILE *sysfile;
  char *realname = 0;
  
  if (*filespec == 0) {
    home = getenv("HOME");
    if (home) {
      realname = g_malloc(100);
      sprintf(realname, "%s/.gnuae/system.startup", home);
    }
  } else {
    realname = strdup(filespec);
  }
  

  lineptr = g_malloc(100);
  buf = g_malloc(100);
  
  sysfile = fopen(realname, "r");
  
  if (sysfile != NULL) {
    sprintf(buf, "Reading config file %s", realname);
    UpdateStatusMsg(1, buf);

    /* The PV module */
    fgets(lineptr, 50, sysfile); /* Read in a line from the file */
    lineptr[strlen(lineptr) - 1] = 0; /* drop the newline on the end
                                         of each line */
    entry = lookup_widget(GTK_WIDGET(MainWindow), "combo_entry1");
    gtk_entry_set_text(GTK_ENTRY(entry), lineptr);
    
    /* The battery */
    fgets(lineptr, 50, sysfile);
    lineptr[strlen(lineptr) - 1] = 0;
    entry = lookup_widget(GTK_WIDGET(MainWindow), "combo_entry2");
    gtk_entry_set_text(GTK_ENTRY(entry), lineptr);

    /* The inverter */
    fgets(lineptr, 50, sysfile);
    lineptr[strlen(lineptr) - 1] = 0;
    entry = lookup_widget(GTK_WIDGET(MainWindow), "inverter_entry");
    gtk_entry_set_text(GTK_ENTRY(entry), lineptr);

    /* The power center */
    fgets(lineptr, 50, sysfile);
    lineptr[strlen(lineptr) - 1] = 0;
    entry = lookup_widget(GTK_WIDGET(MainWindow), "center_entry");
    gtk_entry_set_text(GTK_ENTRY(entry), lineptr);

    /* The PV Combiner box */
    fgets(lineptr, 50, sysfile);
    lineptr[strlen(lineptr) - 1] = 0;
    entry = lookup_widget(GTK_WIDGET(MainWindow), "combiner_entry");
    gtk_entry_set_text(GTK_ENTRY(entry), lineptr);
    
    fgets(lineptr, 50, sysfile);
    lineptr[strlen(lineptr) - 1] = 0;
    entry = lookup_widget(GTK_WIDGET(MainWindow), "charger_entry");
    gtk_entry_set_text(GTK_ENTRY(entry), lineptr);    
  }

  read_system_wiring(sysfile, &wiredata);

  fclose(sysfile);

  return 1;
}

/*
  This writes the contents of the combo boxes to a startup file, so
  the next time we restart, we've got the same settings.
*/
int
write_system(const char *filespec)
{
  GtkWidget *entry;
  gchar *ptr;
  FILE *sysfile;
  char *home;
  char buf[100];
  char *realname = 0;
  //  struct stat stats;

  if (*filespec == 0) {
    home = getenv("HOME");
    if (home) {
      realname = g_malloc(100);
      sprintf(realname, "%s/.gnuae/system.startup", home);
      //      if (stat(filespec, &stats) != 0) {
      //        return;
      //      }
    }
  } else {
    realname = strdup(filespec);
  }
  

  sysfile = fopen(realname, "w");
  
  if (sysfile != NULL) {
    sprintf(buf, "Writing config file %s", realname);
    UpdateStatusMsg(1, buf);
    
    /* The PV module */
    entry = lookup_widget(GTK_WIDGET(MainWindow), "combo_entry1");
    ptr = gtk_entry_get_text(GTK_ENTRY(entry));
    fwrite(ptr, 1, strlen(ptr), sysfile);
    fwrite("\n", 1, 1, sysfile);
    
    /* The battery */
    entry = lookup_widget(GTK_WIDGET(MainWindow), "combo_entry2");
    ptr = gtk_entry_get_text(GTK_ENTRY(entry));
    fwrite(ptr, 1, strlen(ptr), sysfile);
    fwrite("\n", 1, 1, sysfile);

    entry = lookup_widget(GTK_WIDGET(MainWindow), "inverter_entry");
    ptr = gtk_entry_get_text(GTK_ENTRY(entry));
    fwrite(ptr, 1, strlen(ptr), sysfile);
    fwrite("\n", 1, 1, sysfile);    
    
    entry = lookup_widget(GTK_WIDGET(MainWindow), "center_entry");
    ptr = gtk_entry_get_text(GTK_ENTRY(entry));
    fwrite(ptr, 1, strlen(ptr), sysfile);
    fwrite("\n", 1, 1, sysfile);
    
    entry = lookup_widget(GTK_WIDGET(MainWindow), "combiner_entry");
    ptr = gtk_entry_get_text(GTK_ENTRY(entry));
    fwrite(ptr, 1, strlen(ptr), sysfile);
    fwrite("\n", 1, 1, sysfile);
    
    entry = lookup_widget(GTK_WIDGET(MainWindow), "charger_entry");
    ptr = gtk_entry_get_text(GTK_ENTRY(entry));
    fwrite(ptr, 1, strlen(ptr), sysfile);
    fwrite("\n", 1, 1, sysfile);    
  }

  write_system_wiring(sysfile, &wiredata);
  
  fclose(sysfile);

  return 1;
}

/*
  This writes the contents of the combo boxes to a startup file, so
  the next time we restart, we've got the same settings.
*/
void
write_system_wiring(FILE *sysfile, wire_data_t *data)
{
  char buf[100];

  /* Write the header just in case somebody tries to import this
     into a spreadsheet */
  sprintf(buf,"\"distance\",\"awg\",\"conductors\"\n");
  fwrite(buf, 1, strlen(buf), sysfile);
  
  sprintf(buf, "%d,%d,%d\n", data->pv2pv.distance,
          data->pv2pv.awg,
          data->pv2pv.conductors);
  fwrite(buf, 1, strlen(buf), sysfile);
  
  sprintf(buf, "%d,%d,%d\n", data->combiner2charger.distance,
          data->combiner2charger.awg,
          data->combiner2charger.conductors);
  fwrite(buf, 1, strlen(buf), sysfile);
  
  sprintf(buf, "%d,%d,%d\n", data->wind2charger.distance,
          data->wind2charger.awg,
          data->wind2charger.conductors);
  fwrite(buf, 1, strlen(buf), sysfile);
  
  sprintf(buf, "%d,%d,%d\n", data->charger2battery.distance,
          data->charger2battery.awg,
          data->charger2battery.conductors);
  fwrite(buf, 1, strlen(buf), sysfile);
  
  sprintf(buf, "%d,%d,%d\n", data->battery2invert.distance,
          data->battery2invert.awg,
          data->battery2invert.conductors);
  fwrite(buf, 1, strlen(buf), sysfile);
  
  sprintf(buf, "%d,%d,%d\n", data->invert2bld120.distance,
          data->invert2bld120.awg,
          data->invert2bld120.conductors);
  fwrite(buf, 1, strlen(buf), sysfile);
  
  sprintf(buf, "%d,%d,%d\n", data->invert2bld12.distance,
          data->invert2bld12.awg,
          data->invert2bld12.conductors);
  fwrite(buf, 1, strlen(buf), sysfile);
  
  sprintf(buf, "%d,%d,%d\n", data->invert2bld24.distance,
          data->invert2bld24.awg,
          data->invert2bld24.conductors);
  fwrite(buf, 1, strlen(buf), sysfile);
  
  sprintf(buf, "%d,%d,%d\n", data->ground.distance,
          data->ground.awg,
          data->ground.conductors);    
  fwrite(buf, 1, strlen(buf), sysfile);

  sprintf(buf, "0,0,0\n");
  fwrite(buf, 1, strlen(buf), sysfile);
}

void
read_system_wiring(FILE *sysfile, wire_data_t *data)
{
  gchar *lineptr;
  char *buf;
  
  lineptr = g_malloc(100);
  buf = g_malloc(100);
  
  /* Read the headers off the file and then ignore them */
  fgets(lineptr, 50, sysfile);
  
  /* The pv2pv data */
  fgets(lineptr, 50, sysfile); /* Read in a line from the file */
  lineptr[strlen(lineptr) - 1] = 0; /* drop the newline on the end
                                       of each line */
  data->pv2pv.distance = atoi(strtok(lineptr, ","));
  data->pv2pv.awg = atoi(strtok(NULL, ","));
  data->pv2pv.conductors = atoi(strtok(NULL, ","));
  
  /* The combiner2charger data */
  fgets(lineptr, 50, sysfile); /* Read in a line from the file */
  lineptr[strlen(lineptr) - 1] = 0; /* drop the newline on the end
                                       of each line */
  data->combiner2charger.distance = atoi(strtok(lineptr, ","));
  data->combiner2charger.awg = atoi(strtok(NULL, ","));
  data->combiner2charger.conductors = atoi(strtok(NULL, ","));
  
  /* The wind2charger data */
  fgets(lineptr, 50, sysfile); /* Read in a line from the file */
  lineptr[strlen(lineptr) - 1] = 0; /* drop the newline on the end
                                       of each line */
  data->wind2charger.distance = atoi(strtok(lineptr, ","));
  data->wind2charger.awg = atoi(strtok(NULL, ","));
  data->wind2charger.conductors = atoi(strtok(NULL, ","));
  
  fgets(lineptr, 50, sysfile); /* Read in a line from the file */
  lineptr[strlen(lineptr) - 1] = 0; /* drop the newline on the end
                                       of each line */
  data->charger2battery.distance = atoi(strtok(lineptr, ","));
  data->charger2battery.awg = atoi(strtok(NULL, ","));
  data->charger2battery.conductors = atoi(strtok(NULL, ","));
  
  fgets(lineptr, 50, sysfile); /* Read in a line from the file */
  lineptr[strlen(lineptr) - 1] = 0; /* drop the newline on the end
                                       of each line */
  data->battery2invert.distance = atoi(strtok(lineptr, ","));
  data->battery2invert.awg = atoi(strtok(NULL, ","));
  data->battery2invert.conductors = atoi(strtok(NULL, ","));
  
  fgets(lineptr, 50, sysfile); /* Read in a line from the file */
  lineptr[strlen(lineptr) - 1] = 0; /* drop the newline on the end
                                       of each line */
  data->invert2bld120.distance = atoi(strtok(lineptr, ","));
  data->invert2bld120.awg = atoi(strtok(NULL, ","));
  data->invert2bld120.conductors = atoi(strtok(NULL, ","));
  
  fgets(lineptr, 50, sysfile); /* Read in a line from the file */
  lineptr[strlen(lineptr) - 1] = 0; /* drop the newline on the end
                                       of each line */
  data->invert2bld12.distance = atoi(strtok(lineptr, ","));
  data->invert2bld12.awg = atoi(strtok(NULL, ","));
  data->invert2bld12.conductors = atoi(strtok(NULL, ","));
  
  fgets(lineptr, 50, sysfile); /* Read in a line from the file */
  lineptr[strlen(lineptr) - 1] = 0; /* drop the newline on the end
                                       of each line */
  data->invert2bld24.distance = atoi(strtok(lineptr, ","));
  data->invert2bld24.awg = atoi(strtok(NULL, ","));
  data->invert2bld24.conductors = atoi(strtok(NULL, ","));
  
  fgets(lineptr, 50, sysfile); /* Read in a line from the file */
  lineptr[strlen(lineptr) - 1] = 0; /* drop the newline on the end
                                       of each line */
  data->ground.distance = atoi(strtok(lineptr, ","));
  data->ground.awg = atoi(strtok(NULL, ","));
  data->ground.conductors = atoi(strtok(NULL, ","));
}

