// 
//   Copyright (C) 2003, 2004, 2005, 2006, 2007, 2008,
//              2009 Free Software Foundation, Inc.
// 
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

#ifndef __CENTERS_H__
#define __CENTERS_H__

// This is generated by autoconf
#include "config.h"

typedef struct
{
  char *name;
  char *manufacturer;
  double price;
  int voltage;
} center_t;

#ifdef __cplusplus

#include "DataType.h"
#include "Database.h"

#include <map>

namespace gnuae {

class Centers : public DataTypeMethods<center_t> {
public:
    Centers(void);
    ~Centers(void);
    int readCSV(std::string);
    int readSQL(Database &db);
    
    void dump();
    void dump(center_t *cent);
private:
    //      std::map<std::string, centers_t> batteries;
};

} // end of gnuae namespace

extern "C" {
#else
// C API goes here
  extern center_t centers[];
#endif

#ifdef __cplusplus
}
#endif
  
// __CENTERS_H__
#endif

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:
