// 
//   Copyright (C) 2003, 2004, 2005, 2006, 2007, 2008,
//              2009 Free Software Foundation, Inc.
// 
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
// This is generated by autoconf

#include "config.h"

#include <vector>
#include <string>
#include <iostream>
#include <cstdlib>
#include <cmath>

#include "Chargers.h"
#include "Database.h"
#include "log.h"
#include "gnuae.h"

using namespace std;

namespace gnuae {

static LogFile& dbglogfile = LogFile::getDefaultInstance();
static GnuAE& gdata = GnuAE::getDefaultInstance();

#if 0
extern "C" {

  charger_t chargers[] = {
    // Outback charge controllers
    { "None",                       "",        0,  0,  0,  0,   0., 0,
                                         NO, NO, NO, OPTIONAL, OPTIONAL },
    { "MX60",               "Outback",     649.0, 60, 60, 24,   1., 125.0,
                                        YES, YES, NO, OPTIONAL, OPTIONAL },
    // RV Products charge controllers
    { "solarboost 50L",     "RV Products", 419.0, 50, 24, 24, 0.97, 125.0,
                                        NO, YES, NO, OPTIONAL, OPTIONAL },
    { "Solarboost 50DL",    "RV Products", 499.0, 50, 24, 24, 0.97, 125.0,
                                        YES, YES, NO, OPTIONAL, OPTIONAL },
    { "Solarboost 2000E",   "RV Products",   229.0, 30, 48, 24, 0.95, 125.0,
                                        OPTIONAL, YES, NO, OPTIONAL, OPTIONAL },
    { "Solarboost 3048",    "RV Products", 479.0, 30, 48, 48, 0.97, 125.0,
                                        NO, YES, NO, OPTIONAL, OPTIONAL },
    { "Solarboost 3048DL",  "RV Products", 559.0, 30, 48, 48, 0.97, 125.0,
                                        YES, YES, NO, OPTIONAL, OPTIONAL },
    { "Solarboost 6024HL",  "RV Products", 509.0, 60, 48, 24, 0.95, 125.0,
                                        NO, YES, NO, OPTIONAL, OPTIONAL },
    { "Solarboost 6024HDL", "RV Products", 589.0, 60, 48, 24, 0.95, 125.0,
                                        YES, YES, NO, OPTIONAL, OPTIONAL },
    // Xantrex (Trace Engineering) charge controllers
    { "C35",                "Xantrex",      119.0, 35, 24, 24, 1.0, 0.0,
                                        YES, NO, NO, OPTIONAL, OPTIONAL },
    { "C40",                "Xantrex",      159.0, 40, 48, 24, 1.0, 0.0,
                                        YES, NO, NO, OPTIONAL, OPTIONAL },
    { "C60",                "Xantrex",      199.0, 60, 24, 24, 1.0, 0.0,
                                        YES, NO, NO, OPTIONAL, OPTIONAL },
    // Morningstar charge controllers
    { "TS-45",              "Morningstar",  159.0, 45, 24, 24, 1.0, 0.0,
                                        YES, NO, NO, OPTIONAL, OPTIONAL },
    { "TS-60",              "Morningstar",  199.0, 60, 24, 24, 1.0, 0.0,
                                        YES, NO, NO, OPTIONAL, OPTIONAL },
    { "PS-15",              "Morningstar",  112.0, 15, 24, 24, 1.0, 0.0,
                                        NO, NO, YES, YES, NO },
    { "PS-15M",             "Morningstar",  179.0, 15, 24, 24, 1.0, 0.0,
                                        YES, NO, YES, YES, NO },
    { "PS-15M-48V",         "Morningstar",  222.0, 15, 48, 48, 1.0, 0.0,
                                        YES, NO, YES, YES, NO },
    { "PS-30",              "Morningstar",  152.0, 30, 24, 24, 1.0, 0.0,
                                        NO, NO, YES, YES, NO },
    { "PS-30M",             "Morningstar",  152.0, 30, 24, 24, 1.0, 0.0,
                                        YES, NO, YES, YES, NO },
    { "SS-6-12V",           "Morningstar",  48.0, 6, 12, 12, 1.0, 0.0,
                                        NO, NO, YES, YES, NO },
    { "SS-6L-12V",          "Morningstar",  59.0, 6, 12, 12, 1.0, 0.0,
                                        YES, NO, YES, YES, NO },
    { "SS-10-12V",          "Morningstar",  55.0, 10, 12, 12, 1.0, 0.0,
                                        NO, NO, YES, YES, NO },
    { "SS-10L-12V",         "Morningstar",  70.0, 10, 12, 12, 1.0, 0.0,
                                        YES, NO, YES, YES, NO },
    { "SS-10L-24V",         "Morningstar",  76.0, 10, 24, 24, 1.0, 0.0,
                                        YES, NO, YES, YES, NO },
    { "SS-20L-12V",         "Morningstar",  95.0, 20, 12, 12, 1.0, 0.0,
                                        YES, NO, YES, YES, NO },
    { "SS-20L-24V",         "Morningstar", 101.0, 20, 24, 24, 1.0, 0.0,
                                        YES, NO, YES, YES, NO },
    { "SG-4",               "Morningstar",  30.0, 4.5, 12, 12, 1.0, 0.0,
                                        NO, NO, NO, NO, NO },
    {                   0,              0,    0., 0,   0., 0,   1., 0.0,
                                        NONE,     NONE,    NONE, NONE }
  };
};
#endif

Chargers::Chargers() {

}

Chargers::~Chargers() {

}

int
Chargers::readCSV(std::string)
{
    DEBUGLOG_REPORT_FUNCTION;
}

int
Chargers::readSQL(Database &db)
{
    // DEBUGLOG_REPORT_FUNCTION;
    if (db.getState() == Database::DBOPENED) {
    	string query = "SELECT * from chargers";
    	vector<vector<string> > *result = db.queryResults(query);
    	vector<vector<string> >::iterator it;
    	for (it=result->begin(); it!=result->end(); ++it) {
    	    charger_t *thisch = new charger_t;
    	    vector<string> &row = *it;
    	    thisch->name = const_cast<char *>(row[1].c_str());
    	    thisch->manufacturer = const_cast<char *>(row[2].c_str());
    	    // thiscent->price = strtof(row[3].c_str(), NULL);
    	    thisch->amperage = strtol(row[4].c_str(), NULL, 0);
    	    thisch->volts_in = strtol(row[5].c_str(), NULL, 0);
    	    thisch->volts_out = strtol(row[6].c_str(), NULL, 0);
    	    thisch->efficiency = strtof(row[7].c_str(), NULL);
    	    thisch->openmax = strtof(row[8].c_str(), NULL);
	    thisch->lcd = static_cast<feature_e>(strtol(row[9].c_str(), NULL, 0));
	    thisch->MPPT = static_cast<feature_e>(strtol(row[10].c_str(), NULL, 0));
	    thisch->PWM = static_cast<feature_e>(strtol(row[11].c_str(), NULL, 0));
	    thisch->tempsensor = static_cast<feature_e>(strtol(row[12].c_str(), NULL, 0));
	    thisch->remote = static_cast<feature_e>(strtol(row[13].c_str(), NULL, 0));
    	    addEntry(thisch);
    	}
    }

    // dbglogfile << "Loaded " << dataSize() << " records from centers table." << endl;

    return dataSize();
}

void
Chargers::dump()
{
    // DEBUGLOG_REPORT_FUNCTION;
    if (!dataSize()) {
    	cerr << "No Charger Controller data in memory." << endl;
    } else {
    	vector<string>::iterator it;
    	vector<string> *loadnames = dataNames();
    	for (it = loadnames->begin(); it != loadnames->end(); ++it) {
    	    dump(findEntry(*it));
    	}
    }
}

void
Chargers::dump(charger_t *cent)
{
    // DEBUGLOG_REPORT_FUNCTION;
    const char *feature_str[] = {
    	"NONE",
    	"YES",
    	"NO",
    	"OPTIONAL",
    	"DEFAULT"
    };

    cerr << "Charge Controller name is: " << cent->name;
    cerr << ", Manufacturer is: " << cent->manufacturer << endl;
    // cerr << cent->price;
    cerr << "Amperage is: " << cent->amperage;
    cerr << ", Voltage in is: " << cent->volts_in;
    cerr << ", Voltage out is: " << cent->volts_out << endl;
    cerr << "LCD option is: " << feature_str[cent->lcd] << endl;
    cerr << "MPPT option is: " << feature_str[cent->MPPT] << endl;
    cerr << "PWM option is: " << feature_str[cent->PWM] << endl;
    cerr << "Temp Sensor option is: " << feature_str[cent->tempsensor] << endl;
    cerr << "Remote option is: " << feature_str[cent->remote] << endl;
}

} // end of gnuae namespace

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:
