// 
//   Copyright (C) 2004 Free Software Foundation, Inc.
//
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation; either version 2 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//

#ifndef __COMBINERS_H__
#define __COMBINERS_H__

// This is generated by autoconf
#include "config.h"
  
typedef struct
{
  char *name;
  char *manufacturer;
  double price;
  int circuits;                 /* The number of input circuits the box supports */
  int conductors;               /* Some combiner boxes have multiple output lines */
} combiner_t;

#ifdef __cplusplus

#include <map>

namespace gnuae
{
  class Combiners
    {
    public:
      Combiners(void);
      ~Combiners(void);      
    private:
      //      std::map<std::string, combiners_t> batteries;
    };
};

extern "C" {
#else
// C API goes here
  extern combiner_t combiners[];
#endif

#ifdef __cplusplus
}
#endif
  
// __COMBINERS_H__
#endif
