// 
//   Copyright (C) 2005, 2006, 2007, 2008, 2009 Free Software Foundation, Inc.
// 
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

// This is generated by autoconf
#include "config.h"

#include <vector>
#include <string>
#include <iostream>
#include <cstdlib>
#include <cmath>

#include "Combiners.h"

using namespace std;
using namespace gnuae;

extern "C" {
  
  combiner_t combiners[] = {
    { "None",               "None",         0.0, 0, 0 },
    { "PSPV",               "Outback",    139.0, 12, 2 },
    { "TCB10",              "Trace",      229.0, 10, 2 },
    { "TCB6",               "Trace",      189.0,  6, 1 },
    { "Custom",             "Yourself",   250.0, 12, 2 },
    { "PCB10",              "Pulse",      199.0, 10, 2 },
    { 0, 0, 0.0, 0, 0 }
  };
};

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:
