// 
//   Copyright (C) 2004 Free Software Foundation, Inc.
//
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation; either version 2 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//

// Power Loss = Voltage drop as a percentage x load in amps
//

// This is generated by autoconf
#include "config.h"

#include <iostream>
#include <map>
#include <vector>
#include <string>
#include <iterator>
#include <cmath>

#include "Loads.h"
#include "DataType.h"

using namespace std;
using namespace gnuae;

std::vector<std::string> *names(void)
{
  // std::map<std::string, datatype *>::const_iterator it;
  std::map<std::string, void *>::const_iterator it;
  std::vector<std::string> *entrynames;
  datatype *entry;
  entrynames = new std::vector<std::string>;  
  
  if (_data.size() == 0) {
    std::cerr << "No Load data in memory!" << std::endl;
    return entrynames;
  }
      
  for (it = _data.begin(); it != _data.end(); it++) {
    entry = it->second;
    entrynames->push_back(entry->name);
  }
  return entrynames;
}
  
