// 
//   Copyright (C) 2003 Free Software Foundation, Inc.
//
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation; either version 2 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//

#ifndef __GTKPLOT_H__
#define __GTKPLOT_H__

// This is generated by autoconf
#include "config.h"

struct plot_range 
{
  double min;
  double max;
}

struct 3d_plot_data 
{
  char *xtitle;
  char *ytitle;
  char *ztitle;
  struct plot_range xrange;
  struct plot_range yrange;
  struct plot_range zrange;
};


// __GTKPLOT_H__
#endif
