// 
//   Copyright (C) 2004 Free Software Foundation, Inc.
//
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation; either version 2 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//

#ifndef __INVERTERS_H__
#define __INVERTERS_H__

// This is generated by autoconf
#include "config.h"

#include "Chargers.h"

typedef struct
{
  char *name;
  char *manufacturer;
  double price;
  int wattage;
  int voltage;
  feature_e LCD;
  feature_e charger;
  feature_e remote;
  feature_e tempsensor;
  feature_e sinewave;
} inverter_t;

#ifdef __cplusplus

#include <map>

namespace gnuae
{
  class Inverters
    {
    public:
      Inverters(void);
      ~Inverters(void);      
    private:
      //      std::map<std::string, inverters_t> batteries;
    };
};

extern "C" {
#else
// C API goes here
  extern inverter_t inverters[];
#endif

#ifdef __cplusplus
}
#endif
  
// __INVERTERS_H__
#endif
