// 
//   Copyright (C) 2004 Free Software Foundation, Inc.
//
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation; either version 2 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//

#ifndef __PHANTASM_H__
#define __PHANTASM_H__

// This is generated by autoconf
#include "config.h"

#include "PVPanel.h"

namespace gnuae 
{
  // This class does the Phantasm PV Performance calculations
  class PhantasmCalc
    {
    public:
      PhantasmCalc(void);
      ~PhantasmCalc(void);
    private:
      pvpanel_t *paneldata;
    };
  
};

  
  // __PHANTASM_H__
#endif
