// 
//   Copyright (C) 2003 Free Software Foundation, Inc.
//
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation; either version 2 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//

#ifndef __PUMPS_H__
#define __PUMPS_H__

// This is generated by autoconf
#include "config.h"
  
typedef struct
{
  char *name;
  char *manufacturer;
  double price;
  double wattage;
  double voltage;
  double gpm;
} pump_t;

#ifdef __cplusplus

#include <map>

namespace gnuae
{
  class Pumps
    {
    public:
      Pumps(void);
      ~Pumps(void);      
    private:
      //      std::map<std::string, pumps_t> batteries;
    };
};

extern "C" {
#else
// C API goes here
  extern pump_t pumps[];
#endif

#ifdef __cplusplus
}
#endif
  
// __PUMPS_H__
#endif
