// 
//   Copyright (C) 2003, 2004, 2005, 2006, 2007, 2008,
//              2009 Free Software Foundation, Inc.
// 
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

// Power Loss = Voltage drop as a percentage x load in amps
//

// This is generated by autoconf
#include "config.h"

#include <vector>
#include <string>
#include <iostream>
#include <cstdlib>
#include <cmath>

#include "Pumps.h"
#include "Database.h"
#include "log.h"
#include "gnuae.h"

using namespace std;

namespace gnuae {

static LogFile& dbglogfile = LogFile::getDefaultInstance();
static GnuAE& gdata = GnuAE::getDefaultInstance();

Pumps::Pumps()
{
    // DEBUGLOG_REPORT_FUNCTION;
}

Pumps::~Pumps()
{
    // DEBUGLOG_REPORT_FUNCTION;
}

int
Pumps::readCSV(std::string)
{
    DEBUGLOG_REPORT_FUNCTION;
}

int
Pumps::readSQL(Database &db)
{
    // DEBUGLOG_REPORT_FUNCTION;
    if (db.getState() == Database::DBOPENED) {
    	string query = "SELECT * from pumps";
    	vector<vector<string> > *result = db.queryResults(query);
    	vector<vector<string> >::iterator it;
    	for (it=result->begin(); it!=result->end(); ++it) {
    	    pump_t *thisp = new pump_t;
    	    vector<string> &row = *it;
    	    thisp->name = row[1].c_str();
    	    thisp->manufacturer = row[2].c_str();
    	    // thiscent->price = strtof(row[3].c_str(), NULL);
    	    thisp->wattage = strtof(row[4].c_str(), NULL);
    	    thisp->voltage = strtof(row[5].c_str(), NULL);
    	    thisp->gpm = strtof(row[6].c_str(), NULL);
    	    addEntry(thisp);
    	}
	delete result;
    }

    dbglogfile << "Loaded " << dataSize() << " records from pumps table." << endl;

    return dataSize();
}

void
Pumps::dump()
{
    // DEBUGLOG_REPORT_FUNCTION;
    if (!dataSize()) {
    	cerr << "No Water Pump data in memory." << endl;
    } else {
    	vector<string>::iterator it;
    	auto_ptr<vector<string> > loadnames = dataNames();
    	for (it = loadnames->begin(); it != loadnames->end(); ++it) {
    	    dump(findEntry(*it));
    	}
    }
}

void
Pumps::dump(pump_t *pump)
{
    // DEBUGLOG_REPORT_FUNCTION;
    cerr << "Water Pump name is: " << pump->name;
    cerr << ", Manufacturer is: " << pump->manufacturer << endl;
    // cerr << pup->price;
    cerr << "\tWattage is: " << pump->wattage;
    cerr << ", Voltage is: " << pump->voltage;
    cerr << ", GPM is: " << pump->gpm << endl;
}

} // end of gnuae namespace

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:
