// 
//   Copyright (C) 2004 Free Software Foundation, Inc.
//
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation; either version 2 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//

#ifndef __SANDIA_H__
#define __SANDIA_H__

// This is generated by autoconf
#include "config.h"

#include "PVPanel.h"

#ifdef __cplusplus

namespace gnuae
{
  // This class does the Sandia PV Performance calculations
  class SandiaCalc
    {
    public:
      SandiaCalc(void);
      ~SandiaCalc(void);
      
      double calcAMa(double Zs, double h, double e);
      double calcAOI(double Tm, double Zs, double AZm, double AZs);
      double calcIrradianceValues(double wm, double aoi);
      double calcCellTemperature(double ws, double ta, double dto,
                                 double a, double b);
      double calcAbsAirMass(double zs, double h);
      double calcF1(double ama, double a0, double a1,
                    double a2, double a3, double a4);
      double calcF2(double aoi, double b0, double b1, double b2,
                    double b3, double b4, double b5);
      double calcIsco(double Eb, double f1_AMa, double f2_AOI, double fd,
                    double Ed, double Isc, double Tc);
      double calcEffectiveIrradiance(double);
      double calcImp(double);
      double calcVoc(double);
      double calcVmp(double);
      double calcIx(double);
      double calcIxx(double);
      
    private:
      pvpanel_t *currentpv;
    };  
};

#else
// C API goes here
double sandia_calc_AMa(double Zs, double h, double e);
double sandia_calc_AOI(double Tm, double Zs, double AZm, double AZs);
double sandia_calc_irradiance_values(double wm, double aoi);
double sandia_calc_cell_temperature(double ws, double ta, double dto,
                                    double a, double b);
double sandia_calc_abs_air_mass(double zs, double h);
double sandia_calc_F1(double aoi, double a0, double a1,
                      double a2, double a3, double a4);
double sandia_calc_F2(double aoi, double b0, double b1, double b2,
                      double b3, double b4, double b5);
#endif
     
// __SANDIA_H__
#endif
