// 
//   Copyright (C) 2003 Free Software Foundation, Inc.
//
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation; either version 2 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//

// This is generated by autoconf
#include "config.h"

#include <string>
#include <vector>

#include "Wire.h"

#if 0
  char *awg;
  int conductors;
  int mills;
  float uncoated;
  float coated;
#endif

struct wire table[] =
{
  { "18",   7, 1620,   7.95,     8.45   },
  { "16",   7, 2580,   4.99,     5.29   },
  { "14",   7, 4110,   3.14,     3.26   },
  { "12",   7, 6530,   1.98,     2.05   }, 
  { "10",   7, 10380,  1.24,     1.29   },
  { "8",    7, 16510,  0.778,    0.809  },
  { "6",    7, 26240,  0.491,    0.51   },
  { "4",    7, 41740,  0.308,    0.321  },
  { "3",    7, 52620,  0.245,    0.254  },
  { "2",    7, 66360,  0.194,    0.201  },
  { "1",   19, 83690,  0.164,    0.154  },
  { "1/0", 19, 105699, 0.122,    0.127  },
  { "2/0", 19, 133100, 0.0967,   0.101  },
  { "3/0", 19, 167800, 0.0766,   0.0797 },
  { "4/0", 19, 211600, 0.211600, 0.0608 }
};

struct tempfactor
{
  int high;
  int low;
  float factor;
};


  
//  Drop = Current in Amps x resistance per foot x length			
//	Voltage drop= Amp x ohms		
